apiVersion: v1
kind: Pod
metadata:
  name: admin-task-pod
spec:
  initContainers:
  - name: init-config
    command:
    - sh
    - -c
    - cp -vr /etc/cassandra/* /bootstrap
    image: cassandra:3.11
    resources:
      requests: &requests
        cpu: 500m
        memory: 1Gi
      limits: *requests
    volumeMounts:
    - name: bootstrap
      mountPath: /bootstrap
  - name: bootstrap
    image: bootstrap:0.1.3
    resources:
      requests: *requests
      limits: *requests
    env: &env
    - name: CASSANDRA_MAX_HEAP
      value: 256M
    - name: CASSANDRA_SEEDS
      value: cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e
    - name: CASSANDRA_CLUSTER_NAME
      value: cassandra-e2e
    - name: CASSANDRA_GC_STDOUT
      value: "false"
    - name: CASSANDRA_NUM_TOKENS
      value: "256"
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CASSANDRA_DC
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['cassandraclusters.db.orange.com.dc']
    - name: CASSANDRA_RACK
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['cassandraclusters.db.orange.com.rack']
    volumeMounts:
    - name: extra-lib
      mountPath: /extra-lib
    - name: bootstrap
      mountPath: /etc/cassandra
    - name: cassandra-config
      mountPath: /configmap
  securityContext: &nonRoot
    runAsNonRoot: true
    runAsUser: 999
  volumes:
  - name: bootstrap
    emptyDir: {}
  - name: extra-lib
    emptyDir: {}
  - name: tmp
    emptyDir: {}
  containers:
  - name: cassandra
    image: cassandra:3.11
    resources:
      requests: *requests
      limits: *requests
    env: *env
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
      procMount: Default
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: data
      mountPath: /var/lib/cassandra
      readOnly: true
    - name: extra-lib
      mountPath: /extra-lib
    - name: tmp
      mountPath: /tmp
    - name: bootstrap
      mountPath: /etc/cassandra
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-pvc-name