apiVersion: v1
kind: Pod
metadata:
  name: admin-task-pod
  labels:
    app: cassandracluster
    cassandracluster: cassandra-demo
    cassandraclusters.db.orange.com.dc: dc1
    cassandraclusters.db.orange.com.rack: rack1
    cluster: casskop
spec:
  containers:
  - name: cassandra
    command: ["/bin/sh"]
    args: ["-c", "nodetool -h cassandra-demo-dc1-rack1-0.cassandra-demo status || true"]
    # env:
    # - name: JOLOKIA_USER
    #   valueFrom:
    #     secretKeyRef:
    #       key: username
    #       name: jolokia-auth
    # - name: JOLOKIA_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       key: password
    #       name: jolokia-auth
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-cassandra-demo-dc1-rack1-0
  - name: bootstrap
    emptyDir: {}
  - name: extra-lib
    emptyDir: {}
  - name: tmp
    emptyDir: {}
  - configMap:
      defaultMode: 493
      name: cassandra-configmap-v1
    name: cassandra-config