name: "Create cluster using KinD"
on: [push, pull_request]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.1.0
      with:
        version: v0.5.1
    - name: Testing
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl cluster-info
        kubectl get pods -n kube-system


  build:
    # working_directory: /home/circleci/cassandra-k8s-operator
    # executor: casskop-build
    runs-on: ubuntu-18.04
    # runs-on: docker://orangeopensource/casskop-build:v0.9.0
    steps:
    - uses: actions/checkout@master

    # - restore_cache:
    #     keys:
    #       - build-{{ .Branch }}
    #       - build

    - name: Download dependencies
      run: |
        docker run \
        --workdir /github/workspace --rm \
        -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW \
        -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION \
        -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /home/runner/work/_temp/_github_home:/github/home \
        -v /home/runner/work/_temp/_github_workflow:/github/workflow \
        -v /home/runner/work/cassandra-k8s-operator/cassandra-k8s-operator:/github/workspace \
        orangeopensource/casskop-build:v0.9.0 /bin/bash -c "[[ ! -d vendor ]] && go mod download"

    - name: Vendor dependencies
      run: |
        docker run \
        --workdir /github/workspace --rm \
        -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW \
        -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION \
        -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /home/runner/work/_temp/_github_home:/github/home \
        -v /home/runner/work/_temp/_github_workflow:/github/workflow \
        -v /home/runner/work/cassandra-k8s-operator/cassandra-k8s-operator:/github/workspace \
        orangeopensource/casskop-build:v0.9.0 /bin/bash -c "[[ ! -d vendor ]] && go mod vendor"

    - name: Build Cassandra Operator
      run: |
        docker run \
        --workdir /github/workspace --rm \
        -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW \
        -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION \
        -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /home/runner/work/_temp/_github_home:/github/home \
        -v /home/runner/work/_temp/_github_workflow:/github/workflow \
        -v /home/runner/work/cassandra-k8s-operator/cassandra-k8s-operator:/github/workspace \
        orangeopensource/casskop-build:v0.9.0 /bin/bash -c "make build"

    # - persist_to_workspace:
    #     root: ./
    #     paths:
    #       - build/_output
    #       - pkg/apis/db/v1alpha1/zz_generated.deepcopy.go
    #       - pkg/apis/db/v1alpha1/zz_generated.deepcopy.go
    #       - vendor

    # - name: Push image to Docker Hub
    #   run: |
    #     if [[ $(echo "$CIRCLE_BRANCH" | grep -c "pull") -gt 0 ]]; then
    #       echo "This is a PR, we don't push to Hub."
    #     else
    #       docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
    #       make push
    #     fi

    # - save_cache:
    #     name: Save build artefacts in cache
    #     key: build-{{ .Branch }}-{{ checksum "go.sum" }}
    #     paths:
    #       - build/_output
    #       - pkg/apis/db/v1alpha1/zz_generated.deepcopy.go
    #       - pkg/apis/db/v1alpha1/zz_generated.deepcopy.go
    #       - vendor